python main.py --project ivanildobarauna \
               --region us-east4 \
               --runner DataflowRunner \
               --staging_location gs://gcp-streaming-pipeline-dataflow/staging \
               --temp_location gs://gcp-streaming-pipeline-dataflow/temp \
               --sdk_container_image=us-central1-docker.pkg.dev/ivanildobarauna/dataflow-ar/custom-beam/img:latest \
               --sdk_location=container \
               --worker_machine_type=e2-custom-1-3072 \
               --num_workers=1 \
               --max_num_workers=1 \
               --autoscaling_algorithm=NONE